"""add_expert_assignments_table

Revision ID: 0917c82ca99b
Revises: df0e538f99d8
Create Date: 2026-07-25 08:54:54.446922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0917c82ca99b'
down_revision: Union[str, None] = 'df0e538f99d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expert_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('expert_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('expert_comment', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expert_assignments_assessment_id'), 'expert_assignments', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_expert_assignments_expert_id'), 'expert_assignments', ['expert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expert_assignments_expert_id'), table_name='expert_assignments')
    op.drop_index(op.f('ix_expert_assignments_assessment_id'), table_name='expert_assignments')
    op.drop_table('expert_assignments')
    # ### end Alembic commands ###
