"""initial

Revision ID: df0e538f99d8
Revises: 
Create Date: 2026-07-24 20:39:40.111022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0e538f99d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('civility', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('insured_address', sa.String(length=255), nullable=True),
    sa.Column('insured_postal_code', sa.String(length=10), nullable=True),
    sa.Column('insured_city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('type_bien', sa.String(length=30), nullable=True),
    sa.Column('surface', sa.Float(), nullable=True),
    sa.Column('nb_pieces', sa.Integer(), nullable=True),
    sa.Column('nb_etages', sa.Integer(), nullable=True),
    sa.Column('annee_construction', sa.Integer(), nullable=True),
    sa.Column('annee_renovation', sa.Integer(), nullable=True),
    sa.Column('type_structure', sa.String(length=30), nullable=True),
    sa.Column('etat_structure', sa.String(length=20), nullable=True),
    sa.Column('fissures', sa.String(length=30), nullable=True),
    sa.Column('affaissement', sa.String(length=20), nullable=True),
    sa.Column('type_toiture', sa.String(length=30), nullable=True),
    sa.Column('age_toiture', sa.Integer(), nullable=True),
    sa.Column('annee_toiture', sa.Integer(), nullable=True),
    sa.Column('etat_toiture', sa.String(length=20), nullable=True),
    sa.Column('isolation_toiture', sa.String(length=15), nullable=True),
    sa.Column('isolation_murs', sa.String(length=15), nullable=True),
    sa.Column('isolation_sol', sa.String(length=15), nullable=True),
    sa.Column('infiltrations', sa.String(length=20), nullable=True),
    sa.Column('presence_sous_sol', sa.Boolean(), nullable=True),
    sa.Column('presence_cave', sa.Boolean(), nullable=True),
    sa.Column('presence_garage', sa.Boolean(), nullable=True),
    sa.Column('occupation', sa.String(length=20), nullable=True),
    sa.Column('climatisation', sa.Boolean(), nullable=True),
    sa.Column('chauffage_principal', sa.String(length=30), nullable=True),
    sa.Column('installation_electrique_annee', sa.Integer(), nullable=True),
    sa.Column('presence_detecteurs_fumee', sa.Boolean(), nullable=True),
    sa.Column('exposition_solaire', sa.String(length=15), nullable=True),
    sa.Column('zone_mitoyennete', sa.String(length=30), nullable=True),
    sa.Column('hauteur_plancher', sa.Float(), nullable=True),
    sa.Column('clapet_anti_retour', sa.Boolean(), nullable=True),
    sa.Column('equipements_elec_sous_sol', sa.Boolean(), nullable=True),
    sa.Column('profondeur_fondations', sa.String(length=30), nullable=True),
    sa.Column('arbres_proches', sa.Boolean(), nullable=True),
    sa.Column('materiau_toit', sa.String(length=30), nullable=True),
    sa.Column('panneaux_solaires', sa.Boolean(), nullable=True),
    sa.Column('capital_assure', sa.Float(), nullable=True),
    sa.Column('dpe_class', sa.String(length=5), nullable=True),
    sa.Column('built_year', sa.Integer(), nullable=True),
    sa.Column('ban_id', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('form_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('address_label', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('building_data', sa.Text(), nullable=True),
    sa.Column('geography_data', sa.Text(), nullable=True),
    sa.Column('risks_data', sa.Text(), nullable=True),
    sa.Column('climate_data', sa.Text(), nullable=True),
    sa.Column('valuation_data', sa.Text(), nullable=True),
    sa.Column('metadata_data', sa.Text(), nullable=True),
    sa.Column('inondation_score', sa.Integer(), nullable=True),
    sa.Column('rga_score', sa.Integer(), nullable=True),
    sa.Column('tempete_score', sa.Integer(), nullable=True),
    sa.Column('incendie_score', sa.Integer(), nullable=True),
    sa.Column('seisme_score', sa.Integer(), nullable=True),
    sa.Column('global_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('global_score', sa.Integer(), nullable=True),
    sa.Column('sub_scores', sa.Text(), nullable=True),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expert_forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('fields', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expert_forms')
    op.drop_table('evaluation_reports')
    op.drop_table('assessments')
    op.drop_table('properties')
    op.drop_table('documents')
    op.drop_table('clients')
    op.drop_table('users')
    # ### end Alembic commands ###
